functionsDirectory = "/Users/chad/src/tally/.netlify/v1/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/chad/src/tally/build/client"
publishOrigin = "config"
commandOrigin = "config"
command = "nx run @tally/web:build"
functions = "/Users/chad/src/tally/.netlify/v1/functions"

[build.environment]
NODE_ENV = "development"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]